// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"context"
	"github.com/Z00mZE/wireone/internal/config"
	"github.com/Z00mZE/wireone/internal/server"
	"github.com/Z00mZE/wireone/internal/storage/message"
)

// Injectors from wire.go:

func Application(ctx context.Context) (*server.Server, error) {
	settings, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	storage := message.NewStorage(ctx, settings)
	serverServer := server.NewCalc(ctx, storage)
	return serverServer, nil
}
