// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package calc

import (
	"context"
	"github.com/Z00mZE/wireone/internal/config"
	"github.com/Z00mZE/wireone/internal/storage/message"
)

// Injectors from wire.go:

func initialize(ctx context.Context) (*Application, error) {
	settings, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	storage := message.NewStorage(ctx, settings)
	application := NewApplication(ctx, storage)
	return application, nil
}
