// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package adder

import (
	"context"
	"github.com/Z00mZE/simple_adder/internal/app"
	"github.com/Z00mZE/simple_adder/internal/conf"
	"github.com/Z00mZE/simple_adder/internal/service/sum"
	"github.com/Z00mZE/simple_adder/internal/transport/rpc"
	"github.com/Z00mZE/simple_adder/pkg/logger"
)

// Injectors from wire.go:

func InitApplication(ctx context.Context) (*app.Adder, func(), error) {
	settings, err := conf.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	slogLogger := logger.NewLogger()
	server, cleanup, err := rpc.NewServer(ctx, settings, slogLogger)
	if err != nil {
		return nil, nil, err
	}
	service := sum.NewService()
	dispatcher := rpc.NewDispatcher(server, service)
	adder := app.NewAdder(ctx, server, server, dispatcher, slogLogger)
	return adder, func() {
		cleanup()
	}, nil
}
